name: packer boxes

on: [push]

jobs:
    check-commit:
        runs-on: ubuntu-latest
        outputs:
            latest_sha: ${{ steps.latest_sha.outputs.latest_sha }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1
            - name: latest sha
              id: latest_sha
              run: |
                  echo "............get latest sha............"
                  result=`python latest-successful-sha.py "ivyxjc" "vagrantfiles"`
                  echo "::set-output name=latest_sha::$result"
                  echo "$result"

    packer-box:
        runs-on: macos-10.15
        needs: check-commit
        env:
            VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
            PACKER_CACHE_DIR: /Users/runner/packer_cache

        strategy:
            fail-fast: false
            matrix:
                file: ["debian/debian-9.13-amd64.json",
                        "debian/debian-10.10-amd64.json",
                        "debian/debian-11.0-amd64.json",
                        "ubuntu/ubuntu-18.04-amd64.json",
                        "ubuntu/ubuntu-20.04-amd64.json",
                        "ubuntu/ubuntu-20.04-live-amd64.json",
                        "ubuntu/ubuntu-20.10-amd64.json",
                        "ubuntu/ubuntu-21.04-amd64.json"]
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: echo system env
              run: |
                echo $PACKER_CACHE_DIR
                mkdir -p $HOME/packer_cache
                echo "++++++++++++++"
                cd $HOME
                pwd
                echo "+++++-=----------+"
                cd $HOME/packer_cache
                pwd
                echo "???????????????????"
                cd $PACKER_CACHE_DIR
                pwd

            - name: task info
              id: task-info
              run: |
                  task_folder=$(echo ${{ matrix.file }} | awk -F/ '{print $1}')
                  task_file=$(echo ${{ matrix.file }} | awk -F/ '{print $2}')
                  task_box=$(echo ${{ matrix.file }} | awk -F/ '{print $2}' | perl -n -e '/(.*)-amd64.json/ && print $1')
                  echo "$task_folder"
                  echo "$task_file"
                  echo "$task_box"
                  echo "::set-output name=task_folder::$task_folder"
                  echo "::set-output name=task_file::$task_file"
                  echo "::set-output name=task_box::$task_box"

            - name: git diff
              continue-on-error: true
              run: |
                  git diff ${{ needs.check-commit.outputs.latest_sha }} HEAD packer_templates/${{ steps.task-info.outputs.task_folder }} > diff.txt 2>&1 || true

            - name: force run
              run: |
                 echo "diff" > diff.txt


            - name: check diff
              id: check-diff
              run: |
                  if [[ ! -s diff.txt ]]; then
                      echo "no file was changed in ${{ matrix.file }}"
                      echo "::set-output name=has_diff::false"
                  else
                      echo "some files were changed in ${{ matrix.file }}"
                      echo "::set-output name=has_diff::true"
                  fi

            - name: Cache Packer boxes
              uses: actions/cache@v2
              if: steps.check-diff.outputs.has_diff == 'true'
              with:
                  path: /Users/runner/packer_cache
                  key: ${{ runner.os }}-packer-cache
                  restore-keys: |
                      ${{ runner.os }}-packer-

            - name: Cache Vagrant boxes
              uses: actions/cache@v2
              if: steps.check-diff.outputs.has_diff == 'true'
              with:
                  path: ~/.vagrant.d
                  key: ${{ runner.os }}-vagrant-cache
                  restore-keys: |
                      ${{ runner.os }}-vagrant-

            - name: echo env
              run: |
                  echo ${{ steps.check-diff.outputs.has_diff }}
                  echo ${{ steps.task-info.outputs.task_folder }}
                  echo ${{ steps.task-info.outputs.task_file }}
                  echo ${{ steps.task-info.outputs.task_box }}

            - name: packer box
              if: steps.check-diff.outputs.has_diff == 'true'
              working-directory: packer_templates/${{ steps.task-info.outputs.task_folder }}
              run: |
                  packer build -only=virtualbox-iso ${{ steps.task-info.outputs.task_file }}

            - name: list box
              if: steps.check-diff.outputs.has_diff == 'true'
              working-directory: builds
              run: |
                  ls -la

            - name: list packer cache2
              if: steps.check-diff.outputs.has_diff == 'true'
              run: |
                  ls -la ~/packer_cache

            - name: vagrant upload
              if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
              working-directory: builds
              run: |
                  bash ../.github/script/vagrant.sh ${{ steps.task-info.outputs.task_box }}