name: vagrant-up

on: [push]

# on:
#     push:
#         paths:
#             - 'centos7/**'
#             - 'centos8/**'

jobs:
    check-commit:
        runs-on: ubuntu-latest
        outputs:
            latest_sha: ${{ steps.latest_sha.outputs.latest_sha }}
        steps:
            - name: latest sha
              id: latest_sha
              run: |
                echo "............get latest sha............"
                wget https://gist.githubusercontent.com/ivyxjc/8bf4c09745fa4429ae96b7b892df3252/raw/2dbd037d77018a1f00eb57e84b3ccaa3321b8b6e/latest-successful-sha.py
                result=`python latest-successful-sha.py "ivyxjc" "vagrantfiles"`
                echo "::set-output name=latest_sha::$result"
                echo "$result"

    vagrant-up:
        runs-on: macos-10.15
        needs: check-commit
        env:
            VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

        strategy:
            matrix:
                path: ["centos7"]
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: go diff
              continue-on-error: true
              run: |
                git diff ${{ needs.check-commit.outputs.latest_sha }} HEAD ${{ matrix.path }} > diff.txt 2>&1 || true
            
            - name: check diff
              id: check-diff
              run: |
                if [[ ! -s diff.txt ]]; then
                    echo "no file was changed in ${{ matrix.path }}"
                    echo "::set-output name=has_diff::false"
                    echo "::set-output name=has_diff2::true"
                else
                    echo "some files werer changed in ${{ matrix.path }}"
                    echo "::set-output name=has_diff::true"
                    echo "::set-output name=has_diff2::true"
                fi 

            - name: echo env
              if: steps.check-diff.outputs.has_diff == 'true'
              run: |
                  echo ${{ steps.check-diff.outputs.has_diff }}

            - name: Cache Vagrant boxes
              uses: actions/cache@v2
              if: steps.check-diff.outputs.has_diff == 'true'
              with:
                  path: ~/.vagrant.d
                  key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
                  restore-keys: |
                      ${{ runner.os }}-vagrant-

            - name: vagrant install plugin
              if: steps.check-diff.outputs.has_diff == 'true'
              run: |
                  vagrant plugin install vagrant-vbguest --plugin-version 0.21

            - name: vagrant up
              if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
              working-directory: ${{ matrix.path }}
              run: |
                  vagrant up

            - name: vagrant status
              if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
              working-directory: ${{ matrix.path }}
              run: |
                  vagrant status

            - name: package box
              if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
              run: |
                  vagrant package --base vagrant-default --output ${{ matrix.path }}.box

            - name: vagrant upload
              if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
              run: |
                  bash ./.github/script/vagrant.sh ${{ matrix.path }}

            - name: vagrant destroy
              if: ${{ steps.check-diff.outputs.has_diff == 'true' }}
              working-directory: ${{ matrix.path }}
              run: |
                  vagrant destroy -f
